import type { Lead } from "@/lib/leads/types";

/**
 * MOCK DATA — for UI visibility only.
 * When integrating / going live: delete this file and remove all imports of `MOCK_LEADS`.
 */
export const MOCK_LEADS: Lead[] = [
  {
    id: "mock-lead-001",
    createdAt: "2026-07-18T09:24:00.000Z",
    type: "price-calculator",
    formKey: "price-calculator-form",
    sourcePage: "/",
    sourceLabel: "Homepage price calculator · /",
    fullName: "Anna Müller",
    email: "anna.mueller@example.com",
    phone: "+49 170 1112233",
    whatsapp: "+49 170 1112233",
    inquiryType: "Price calculation request",
    message:
      "Price calculation request\nPick up: Köln Hbf\nDelivery: Frankfurt Airport\nDimensions (L×W×H cm): 120 × 80 × 60",
    pickupAddress: "Köln Hbf, Köln",
    deliveryAddress: "Frankfurt Airport, Frankfurt",
    length: "120",
    width: "80",
    height: "60",
  },
  {
    id: "mock-lead-002",
    createdAt: "2026-07-17T14:10:00.000Z",
    type: "contact",
    formKey: "contact-page-form",
    sourcePage: "/kontakt",
    sourceLabel: "Contact page · /kontakt",
    fullName: "Marcus Weber",
    email: "marcus.weber@logistik.de",
    phone: "+49 221 998877",
    whatsapp: "+49 221 998877",
    inquiryType: "Freight forwarding",
    message: "Need a quote for weekly pallet shipments between Bergisch Gladbach and München.",
    pickupAddress: "",
    deliveryAddress: "",
    length: "",
    width: "",
    height: "",
  },
  {
    id: "mock-lead-003",
    createdAt: "2026-07-16T11:45:00.000Z",
    type: "contact",
    formKey: "service-lead-courier",
    sourcePage: "/kuriertransporte",
    sourceLabel: "Service page (courier) · /kuriertransporte",
    fullName: "Elena Popescu",
    email: "elena.popescu@mail.ro",
    phone: "+40 721 555667",
    whatsapp: "+40 721 555667",
    inquiryType: "Courier",
    message: "Same-day express documents from Düsseldorf to Bonn tomorrow morning.",
    pickupAddress: "",
    deliveryAddress: "",
    length: "",
    width: "",
    height: "",
  },
  {
    id: "mock-lead-004",
    createdAt: "2026-07-15T08:05:00.000Z",
    type: "contact",
    formKey: "landing-contact-map-form",
    sourcePage: "/",
    sourceLabel: "Homepage contact form · /",
    fullName: "Thomas Schneider",
    email: "t.schneider@firma.de",
    phone: "+49 2234 112233",
    whatsapp: "+49 2234 112233",
    inquiryType: "Quote request",
    message: "Looking for refrigerated transport options for food deliveries.",
    pickupAddress: "",
    deliveryAddress: "",
    length: "",
    width: "",
    height: "",
  },
  {
    id: "mock-lead-005",
    createdAt: "2026-07-14T16:30:00.000Z",
    type: "contact",
    formKey: "industries-lead-form",
    sourcePage: "/branchen",
    sourceLabel: "Industries page · /branchen",
    fullName: "Sofia Rossi",
    email: "sofia.rossi@pharma.eu",
    phone: "+49 30 4455667",
    whatsapp: "+49 30 4455667",
    inquiryType: "Industries",
    message: "GDP-compliant pharma transport inquiry for Berlin ↔ Köln lane.",
    pickupAddress: "",
    deliveryAddress: "",
    length: "",
    width: "",
    height: "",
  },
  {
    id: "mock-lead-006",
    createdAt: "2026-07-13T10:18:00.000Z",
    type: "newsletter",
    formKey: "landing_newsletter_form",
    sourcePage: "/",
    sourceLabel: "Newsletter · /",
    fullName: "",
    email: "newsletter.fan@example.com",
    phone: "",
    whatsapp: "",
    inquiryType: "Newsletter",
    message: "Newsletter subscription",
    pickupAddress: "",
    deliveryAddress: "",
    length: "",
    width: "",
    height: "",
  },
  {
    id: "mock-lead-007",
    createdAt: "2026-07-12T13:55:00.000Z",
    type: "contact",
    formKey: "about-lead-form",
    sourcePage: "/ueber-uns",
    sourceLabel: "About page · /ueber-uns",
    fullName: "Jonas Becker",
    email: "jonas.becker@startup.io",
    phone: "+49 151 99887766",
    whatsapp: "+49 151 99887766",
    inquiryType: "General",
    message: "Interested in partnership for e-commerce fulfillment in NRW.",
    pickupAddress: "",
    deliveryAddress: "",
    length: "",
    width: "",
    height: "",
  },
  {
    id: "mock-lead-008",
    createdAt: "2026-07-11T07:40:00.000Z",
    type: "price-calculator",
    formKey: "price-calculator-form",
    sourcePage: "/en",
    sourceLabel: "Homepage price calculator · /en",
    fullName: "Laura King",
    email: "laura.king@example.co.uk",
    phone: "+44 7700 900123",
    whatsapp: "+44 7700 900123",
    inquiryType: "Price calculation request",
    message:
      "Price calculation request\nPick up: London Heathrow\nDelivery: Bergisch Gladbach\nDimensions: not provided",
    pickupAddress: "London Heathrow, UK",
    deliveryAddress: "Bergisch Gladbach, Germany",
    length: "",
    width: "",
    height: "",
  },
  {
    id: "mock-lead-009",
    createdAt: "2026-07-10T19:22:00.000Z",
    type: "contact",
    formKey: "service-lead-refrigerated",
    sourcePage: "/kuehltransporte",
    sourceLabel: "Service page (refrigerated) · /kuehltransporte",
    fullName: "Dirk Hoffmann",
    email: "dirk.hoffmann@freshfood.de",
    phone: "+49 211 334455",
    whatsapp: "+49 211 334455",
    inquiryType: "Refrigerated",
    message: "Need 2–4°C transport for dairy products, 3 pallets weekly.",
    pickupAddress: "",
    deliveryAddress: "",
    length: "",
    width: "",
    height: "",
  },
  {
    id: "mock-lead-010",
    createdAt: "2026-07-09T12:00:00.000Z",
    type: "contact",
    formKey: "service-lead-international",
    sourcePage: "/internationaler-versand",
    sourceLabel: "Service page (international) · /internationaler-versand",
    fullName: "Amelia Novak",
    email: "amelia.novak@export.pl",
    phone: "+48 601 223344",
    whatsapp: "+48 601 223344",
    inquiryType: "International",
    message: "Cross-border shipment Warsaw → Cologne, customs docs support needed.",
    pickupAddress: "",
    deliveryAddress: "",
    length: "",
    width: "",
    height: "",
  },
];

export function getMockLeadById(id: string) {
  return MOCK_LEADS.find((lead) => lead.id === id) ?? null;
}
